# FROM node  >>> big files create

FROM node:20.9.0-alpine3.18

WORKDIR /backend

COPY . .

RUN mkdir -p logs
RUN npm i

CMD npm start  
EXPOSE 8000
# EXPOSE >>> find in Docker PORT
# docker image prune -f -a >>> tüm image dosyalarini sil
# docker container prune -f -a >>> tüm container dosyalarini sil
# docker system prune -f -a >>> sistemdeki tüm container,image,cache dosyalarini sil
# docker build -t backend .
# docker run --name backend1 -p 7000:8000  backend //disardaki 7000 port icerdeki 8000 e eslesti
# docker run backend
# docker run -d -p 8000:8000 --name backend2 backend